---
blackboard:
  is_testing: false
  is_blackboard: false

scr:
  wndw_name: OpenGL Renderer
  width: 800
  height: 600

settings:
  is_wireframeMode: false

colors:
  bg: #121212
  bg-alter: 0
  bg-second: 0

default_camera:
  near: 0.01
  far: 1000.01
  fov: 45.0
  rotation_sensitivity: 0.02

default_animation:
  animate: false
  angle_multiplier: 0.0
  last_frame_time: 0.0
  emission_factor: 0.0

scene:
    active_scene: 9


# Right hand major.
# matrices: column major.    
# Y up
# -Z forward direction
# Naming convention